language: c
sudo: required
services:
    - docker
os:
    - osx
    - linux
    
compiler:
    - clang
    - gcc

before_install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        sudo apt-add-repository -y ppa:beineri/opt-qt55-trusty
        && sudo apt-get update -qq
        && sudo apt-get install -qq g++-4.8 libboost-all-dev libevent-dev qt55base qt55tools qt55websockets libavahi-compat-libdnssd1 libavahi-compat-libdnssd-dev libqrencode-dev
        ;
      fi
 
install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        export CXX="g++-4.8"
        && export CC="gcc-4.8"
        ;
      else
        brew install hidapi libevent qt5 libqrencode
        ;
      fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libudev-dev
    - libusb-1.0-0-dev
    - libevent-dev

matrix:
    fast_finish:
        - true


before_script:
    - cd $TRAVIS_BUILD_DIR
    - git clone git://github.com/signal11/hidapi.git
    - cd hidapi && ./bootstrap && ./configure --prefix=$TRAVIS_BUILD_DIR && make install && cd ..
    - git submodule init
    - git submodule update

script: 
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        QTDIR="/opt/qt55" && PATH="$QTDIR/bin:$PATH" && qt55-env.sh
        && ./autogen.sh
        && PKG_CONFIG_PATH="/opt/qt55/lib/pkgconfig:$PKG_CONFIG_PATH" ./configure CXX=g++-4.8 --with-dns_sd --with-hid-libdir=$TRAVIS_BUILD_DIR/lib --with-hid-includedir=$TRAVIS_BUILD_DIR/include --enable-daemon --with-gui=qt5 --enable-debug
        ;
     else
        ./autogen.sh
        && ./configure --with-dns_sd --enable-daemon --with-gui=qt5 --enable-debug
        ;
     fi
    - make